url: "https://hearthsim.info"
baseurl: ""
permalink: /blog/:title/

vars:
  name: "HearthSim"
  description: "Hearthstone Simulation & AI"
  logo: "/images/logo.png"
  email: "contact@hearthsim.info"
  google_analytics:
  rss: true

  links:
    github: HearthSim
    youtube: c/HearthstoneScience
    twitter:


# Syntax highlighting
markdown: kramdown
kramdown:
  # Use Github Flavored Markdown (including triple backticks)
  input: GFM
  hard_wrap: false  # No linebreak on newlines unless explicitly specified
  syntax_highlighter: rouge
  syntax_highlighter_opts:
  # Reuse pygments syntax css class
    css_class: "highlight"

sass:
  style: :compressed


# Plug-ins
gems:
  - jekyll-mentions # @-mentions
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem


exclude:
  - LICENSE
  - README.md
  - CNAME
